### ISSUE TITLE
🎨 Refactor: existing styles to css-in-js with @emotion.

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#208]
This comes from an action item in <https://github.com/jina-ai/dashboard/discussions/127>. We have made a decision to move to css-in-js to have atomic styles,  to make it easy to use themes, make it easy to find and update styles.

The general idea is to the styles we currently have in css, scss files to css-in-js, use theming and improve, refactor our current emotion styles when needed

This issue will spawn multiple smaller issues. I'll keep track of them in a checklist below.

-   [x] [🎨 Use colors from theme palette in CommandBar.tsx](https://github.com/jina-ai/dashboard/issues/180)

-   [x] [🎨 Use colors from theme palette in NodePort.tsx](https://github.com/jina-ai/dashboard/issues/181)

-   [x] [🎨 Use colors from theme palette in HubOverviewActions.tsx](https://github.com/jina-ai/dashboard/issues/182)

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7156743
