### ISSUE TITLE
Debugging tool

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#330]
Create a debugging tool to help out the core team with Jina debugging.

![](https://pb-files.s3.amazonaws.com/production/attachments/7bbb98b937bc0b056541404798a201cf65f1ff6258fff9fcd516c6778010e92f/image.png)

Link to an example request response: <https://github.com/jina-ai/jina/blob/master/.github/2.0/cookbooks/Flow.md#curl-with-http-request>

### Swagger
Question marks:

* how do we use external components and package it
* how is swagger generated in jina currently
* how is swagger packaged and built
* how do we allow the user to upload images, video, audio and convert to 64 before the request is sent (in Swagger)
* how do we pull the response and 2) how do we set our own state
* how do we access the states from within our component (Swagger state and our custom state)

### TODO
* [x] Repackage with Jina and available as an SPA.
* [x] jina CI/CD should take care of building the newest debug tool and attaching it to the release
* [ ] add a way to infer the port and address from the url so that the user doesn't have to input it manually
* [ ] use Open API JSON schema to create request structure
* [ ] enable multiple file upload in the request of Swagger

### UI Improvements:
- [ ] in Response canvas, only the first Document in response is rendered. Please render all documents.
- [x] in Response canvas, renders everything from left to right
- [x] in Response canvas, remove the dots background in the canvas
- [x] in Response canvas, do not show the fields under DocumentCard that are "", 0, unset, empty, null
- [ ] in Response canvas, the first view should be a birdview that covers everything.
- [x] in Response canvas, delete Routes (List of Pods), as it is not part of repsonse JSONSchema anymore.

## Acceptance criteria:
* There is a new tab in Console under a feature flag called 'debugger'
* The tab has a field for a host and port URL at the top and a 'Send' button next to it 
* The tab has a JSON body request field
* The tab has a field to display Pods and their routes
* The tab has a field to display all Document results and their scores. 
* The send button upon a click sends the request from JSON body field to a predetermined endpoint at host and port entered by the user. The response is visualized.
* The debug tool is available as an SPA in jina core
* Embed custom component within Swagger

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200498922555298/1200504669659676) by [Unito](https://www.unito.io)

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/8123680

**Comment by aga11313** [comment]
Reopening
